basePath: /
definitions:
  dtos.AuthLoginApiRes:
    properties:
      additionalInfo:
        additionalProperties: true
        type: object
      data:
        $ref: '#/definitions/dtos.AuthResData'
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  dtos.AuthLoginReqData:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dtos.AuthRegisterApiRes:
    properties:
      additionalInfo:
        additionalProperties: true
        type: object
      data:
        $ref: '#/definitions/dtos.AuthResData'
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  dtos.AuthRegisterReqData:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dtos.AuthResData:
    properties:
      email:
        type: string
      id:
        type: string
      token:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a template for a RESTful API using Fiber.
  title: Api Template
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User login details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthLoginReqData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.AuthLoginApiRes'
      summary: Login a user
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User registration details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.AuthRegisterReqData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.AuthRegisterApiRes'
      summary: Register a new user
      tags:
      - Authentication
produces:
- application/json
schemes:
- http
swagger: "2.0"
